import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"; 
import VerticalEventMarquee from "@/components/VerticalEventMarquee";// ✅ ADD THIS LINE
import BlobCursor from "@/components/BlogCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
  {/* BACKGROUND IMAGE */}
  <div
    className="fixed inset-0 -z-10 bg-cover bg-center"
    style={{
      backgroundImage: "url('/images/bg-1.png')",
    }}
  />

  {/* DARK OVERLAY */}
  <div className="fixed inset-0 -z-10 bg-black/60" />

  {/* WEBSITE CONTENT */}
  <Navbar />
  <VerticalEventMarquee />

  {children}
</body>

    </html>
  );
}
